spring:
  application:
    name: restapi
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  datasource:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:h2:mem:restapi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY
          username: restapi
          password:



